version: '3'
# https://riina-k.net/programming/docker-compose-nginx-reverse-proxy-ssl/
services:
  web-proxy:
    image: jwilder/nginx-proxy
    container_name: web-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      #DEFAULT_HOST: ${HOST_NAME}
      #DHPARAM_GENERATION: "false"
      TZ: Japan
    env_file:
      - web-proxy.env
    privileged: true
    #labels:
    #  - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:true"
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      #- conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- ./data/conf/conf.d:/etc/nginx/conf.d
      #- ./data/my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf
      #- ./logs:/var/log/nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: on-failure
    networks:
      - web-proxy-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      # Find nginx proxy container.
      NGINX_PROXY_CONTAINER: web-proxy
      #NGINX_DOCKER_GEN_CONTAINER: web-proxy
      # Settings for test.
      ACME_CA_URI: https://acme-staging-v02.api.letsencrypt.org/directory
    privileged: true
    depends_on:
      - web-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs:rw
      #- conf:/etc/nginx/conf.d      
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./data/functions.sh:/app/functions.sh
      #- ./data/nginx_location.conf:/app/nginx_location.conf
    networks:
      - web-proxy-network
 
volumes:
  conf:
  vhost:
  html:
  dhparam:

networks:
  web-proxy-network:
    external: true

