version: '3'
services:
  web-hw:
    container_name: web-hw
    image: nginx:alpine
    environment: 
      TZ: Japan
      ## Setting for nginx-proxy.
      # VIRTUAL_HOST: foo.bar.buzz.net
      #VIRTUAL_PORT: 80
      ## Settings for Let's Encrypt.
      # LETSENCRYPT_HOST: foo.bar.buzz.net
      # LETSENCRYPT_EMAIL: admin@foo.bar.buzzz.net
      CERT_NAME: default
      # Settings for test.
      LETSENCRYPT_TEST: "true"
    env_file:
      - web-hw.env
    #ports: 
    #  - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/conf.d:/etc/nginx/conf.d
    #  - ./log:/var/log/nginx
    networks:
      web-proxy-network:

networks:
  web-proxy-network:
    external: true

