version: '3'
services:
  web-hw:
    container_name: web-hw
    image: nginx:alpine
    environment: 
      VIRTUAL_HOST: foo.bar.buzz.net
      #VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: foo.bar.buzz.net
      LETSENCRYPT_EMAIL: admin@foo.bar.buzz.net.com
      CERT_NAME: default
      TZ: Japan
    #ports: 
    #  - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf/conf.d:/etc/nginx/conf.d
    #  - ./log:/var/log/nginx
    networks:
      web-proxy-network:

networks:
  web-proxy-network:
    external: true

