version: '3'
services:
  web-sa:
    container_name: web-sa
    build:
      context: .
      dockerfile: Dockerfile.le
    #image: nginx:alpine
    environment: 
      TZ: Japan
      ## Setting for nginx-proxy.
      # VIRTUAL_HOST: foo.bar.buzz.net
      #VIRTUAL_PORT: 80
      ## Settings for Let's Encrypt.
      # LETSENCRYPT_HOST: foo.bar.buzz.net
      # LETSENCRYPT_EMAIL: admin@foo.bar.buzzz.net
      # CERT_NAME: default
      ## Settings for test.
      #LETSENCRYPT_TEST: "true"
    env_file:
      - web-sa.env
    depends_on:
      - web-web01
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/conf/default_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
    tty: true
    #  - ./log:/var/log/nginx
    networks:
      web-proxy-network:

  web-web01:
    container_name: web-web01
    image: nginx:alpine
    environment:
      TZ: Japan
      ## Setting for nginx-proxy.
      # VIRTUAL_HOST: foo.bar.buzz.net
      #VIRTUAL_PORT: 80
      ## Settings for Let's Encrypt.
      # LETSENCRYPT_HOST: foo.bar.buzz.net
      # LETSENCRYPT_EMAIL: admin@foo.bar.buzzz.net
      # CERT_NAME: default
      ## Settings for test.
      #LETSENCRYPT_TEST: "true"
    env_file:
      - web-sa.env
    volumes:
      - ./www:/usr/share/nginx/html
      - ${PWD}/conf/default.conf:/etc/nginx/conf.d/default.conf
    #  - ./log:/var/log/nginx
    networks:
      web-proxy-network:
networks:
  web-proxy-network:
    external: true

